version: '2'

services:

  backend-app:
    image: moody26/backend
    container_name: mioga-lieferanten-backend
    ports:
      - 8080:8080



  frontend-app:
    image: moody26/frontend
    container_name: mioga-lieferanten-frontend
    ports:
      - 4200:80
    links:
      - backend-app


