version: '2'

services:

  backend-app:
    build: ./balena-mioga-lieferanten-backend
    container_name: mioga-lieferanten-backend
    ports:
      - 8080:8080



  frontend-app:
    build: ./balena-mioga-lieferanten-frontend
    container_name: mioga-lieferanten-frontend
    ports:
      - 4200:80
    links:
      - backend-app


